from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 320)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        Dialog.setFont(font)
        Dialog.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\user\\PycharmProjects\\checker_dumau\\../../../../ico/checker_dumau/hota.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/ico/checker_dumau/hota.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        Dialog.setToolTip("")
        Dialog.setStatusTip("")
        Dialog.setWhatsThis("")
        Dialog.setAccessibleName("")
        Dialog.setAccessibleDescription("")
        Dialog.setStyleSheet("")
        Dialog.setWindowFilePath("")
        self.result_label = QtWidgets.QLabel(Dialog)
        self.result_label.setGeometry(QtCore.QRect(0, 240, 400, 30))
        self.result_label.setStyleSheet("")
        self.result_label.setTextFormat(QtCore.Qt.PlainText)
        self.result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.result_label.setWordWrap(True)
        self.result_label.setObjectName("result_label")
        self.underground = QtWidgets.QCheckBox(Dialog)
        self.underground.setGeometry(QtCore.QRect(270, 180, 121, 25))
        self.underground.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.underground.setAutoFillBackground(False)
        self.underground.setCheckable(True)
        self.underground.setChecked(False)
        self.underground.setTristate(False)
        self.underground.setObjectName("underground")
        self.welcome_text = QtWidgets.QLabel(Dialog)
        self.welcome_text.setEnabled(True)
        self.welcome_text.setGeometry(QtCore.QRect(5, 20, 390, 20))
        self.welcome_text.setTextFormat(QtCore.Qt.RichText)
        self.welcome_text.setScaledContents(True)
        self.welcome_text.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_text.setWordWrap(True)
        self.welcome_text.setObjectName("welcome_text")
        self.check_button = QtWidgets.QPushButton(Dialog)
        self.check_button.setGeometry(QtCore.QRect(160, 210, 75, 23))
        self.check_button.setObjectName("check_button")
        self.helpme = QtWidgets.QPushButton(Dialog)
        self.helpme.setGeometry(QtCore.QRect(270, 290, 121, 23))
        self.helpme.setAutoDefault(True)
        self.helpme.setObjectName("helpme")
        self.author = QtWidgets.QLabel(Dialog)
        self.author.setGeometry(QtCore.QRect(275, 265, 111, 31))
        self.author.setScaledContents(True)
        self.author.setAlignment(QtCore.Qt.AlignCenter)
        self.author.setObjectName("author")
        self.x_text = QtWidgets.QLabel(Dialog)
        self.x_text.setGeometry(QtCore.QRect(10, 160, 111, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.x_text.setFont(font)
        self.x_text.setAlignment(QtCore.Qt.AlignCenter)
        self.x_text.setWordWrap(True)
        self.x_text.setObjectName("x_text")
        self.y_text = QtWidgets.QLabel(Dialog)
        self.y_text.setGeometry(QtCore.QRect(140, 160, 111, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.y_text.setFont(font)
        self.y_text.setAlignment(QtCore.Qt.AlignCenter)
        self.y_text.setWordWrap(True)
        self.y_text.setObjectName("y_text")
        self.hotalogo = QtWidgets.QLabel(Dialog)
        self.hotalogo.setGeometry(QtCore.QRect(10, 50, 380, 100))
        self.hotalogo.setBaseSize(QtCore.QSize(400, 320))
        self.hotalogo.setStyleSheet("image: url(:/logo/checker_dumau/logo.jpg);")
        self.hotalogo.setText("")
        self.hotalogo.setTextFormat(QtCore.Qt.PlainText)
        self.hotalogo.setPixmap(QtGui.QPixmap("C:\\Users\\user\\PycharmProjects\\checker_dumau\\../../../../logo/checker_dumau/logo.jpg"))
        self.hotalogo.setScaledContents(True)
        self.hotalogo.setWordWrap(True)
        self.hotalogo.setOpenExternalLinks(False)
        self.hotalogo.setObjectName("hotalogo")
        self.x_box = QtWidgets.QSpinBox(Dialog)
        self.x_box.setGeometry(QtCore.QRect(10, 180, 110, 25))
        self.x_box.setWrapping(False)
        self.x_box.setAlignment(QtCore.Qt.AlignCenter)
        self.x_box.setSpecialValueText("")
        self.x_box.setMinimum(0)
        self.x_box.setMaximum(252)
        self.x_box.setObjectName("x_box")
        self.y_box = QtWidgets.QSpinBox(Dialog)
        self.y_box.setGeometry(QtCore.QRect(140, 180, 110, 25))
        self.y_box.setAlignment(QtCore.Qt.AlignCenter)
        self.y_box.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.y_box.setSpecialValueText("")
        self.y_box.setMaximum(252)
        self.y_box.setObjectName("y_box")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SuperChecker for Hota, ver 0.10"))
        self.result_label.setStatusTip(_translate("Dialog", "Результат программы"))
        self.result_label.setText(_translate("Dialog", "Результат программы"))
        self.underground.setText(_translate("Dialog", "Подземелье"))
        self.welcome_text.setText(_translate("Dialog", "Проверка нейтралов на грейд стек на карте приключений"))
        self.check_button.setText(_translate("Dialog", "Проверить"))
        self.helpme.setText(_translate("Dialog", "How to use?"))
        self.author.setText(_translate("Dialog", "Created by dumau111"))
        self.x_text.setText(_translate("Dialog", "X"))
        self.y_text.setText(_translate("Dialog", "Y"))
import dumau_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
